// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC3WOaHzVztj9MYGx6TTookGoB6lA0sok',
    appId: '1:909147524071:web:35dc52bf16720a67610b42',
    messagingSenderId: '909147524071',
    projectId: 'flutter-notes-app-8957f',
    authDomain: 'flutter-notes-app-8957f.firebaseapp.com',
    storageBucket: 'flutter-notes-app-8957f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjQ8xudRm3GjhnyqQAYwY-Qpgj07QD3rY',
    appId: '1:909147524071:android:7da2e33530115953610b42',
    messagingSenderId: '909147524071',
    projectId: 'flutter-notes-app-8957f',
    storageBucket: 'flutter-notes-app-8957f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMK2oWRm3jLIX_YD9kuhkQgm2xbWC5o80',
    appId: '1:909147524071:ios:49343f5f3b12e74a610b42',
    messagingSenderId: '909147524071',
    projectId: 'flutter-notes-app-8957f',
    storageBucket: 'flutter-notes-app-8957f.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMK2oWRm3jLIX_YD9kuhkQgm2xbWC5o80',
    appId: '1:909147524071:ios:49343f5f3b12e74a610b42',
    messagingSenderId: '909147524071',
    projectId: 'flutter-notes-app-8957f',
    storageBucket: 'flutter-notes-app-8957f.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC3WOaHzVztj9MYGx6TTookGoB6lA0sok',
    appId: '1:909147524071:web:8a4deab5b317570a610b42',
    messagingSenderId: '909147524071',
    projectId: 'flutter-notes-app-8957f',
    authDomain: 'flutter-notes-app-8957f.firebaseapp.com',
    storageBucket: 'flutter-notes-app-8957f.firebasestorage.app',
  );

}