// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD83nUL7F5hS_ZThX-iDYe2JHIDCwKCUyY',
    appId: '1:662028618114:web:fe19cf72ee768bcb89279b',
    messagingSenderId: '662028618114',
    projectId: 'fir-crud-6f9b3',
    authDomain: 'fir-crud-6f9b3.firebaseapp.com',
    storageBucket: 'fir-crud-6f9b3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_bEbxw3d5OIbvnbJ25gH8t2jjG95Hwtk',
    appId: '1:662028618114:android:ac62e67a20e6e67d89279b',
    messagingSenderId: '662028618114',
    projectId: 'fir-crud-6f9b3',
    storageBucket: 'fir-crud-6f9b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT9B3e90CycPVj_Bb7R-bpp6ieSF_feEI',
    appId: '1:662028618114:ios:d636449b5f90915589279b',
    messagingSenderId: '662028618114',
    projectId: 'fir-crud-6f9b3',
    storageBucket: 'fir-crud-6f9b3.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT9B3e90CycPVj_Bb7R-bpp6ieSF_feEI',
    appId: '1:662028618114:ios:d636449b5f90915589279b',
    messagingSenderId: '662028618114',
    projectId: 'fir-crud-6f9b3',
    storageBucket: 'fir-crud-6f9b3.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD83nUL7F5hS_ZThX-iDYe2JHIDCwKCUyY',
    appId: '1:662028618114:web:0edbd368f72c65ac89279b',
    messagingSenderId: '662028618114',
    projectId: 'fir-crud-6f9b3',
    authDomain: 'fir-crud-6f9b3.firebaseapp.com',
    storageBucket: 'fir-crud-6f9b3.firebasestorage.app',
  );

}